Layout/IndentArray:
  Description: Checks the indentation of the first element in an array literal.
  Enabled: true
  EnforcedStyle: consistent

Style/StringLiterals:
  Description: Checks if uses of quotes match the configured preference.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#consistent-string-literals
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Naming/VariableNumber:
  Description: Use normalcase for variable numbers.
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/TrailingCommaInArguments:
  Description: 'Checks for trailing comma in argument lists.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-trailing-array-commas'
  EnforcedStyleForMultiline: consistent_comma
  SupportedStylesForMultiline:
    - comma
    - consistent_comma
    - no_comma
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Enabled: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
  Enabled: true

Style/EmptyMethod:
  Enabled: false
